services:
  s3-ninja:
    image: scireum/s3-ninja:latest
    container_name: s3-ninja
    ports:
      - "9444:9000"
    volumes:
      - ./s3-ninja-data:/home/sirius/data
    environment:
      - NINJA_OPTS=-Dninja.port=9000 -Dninja.contextPath=/ -Dninja.docBase=/home/sirius/data